# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.0.x'

- task: UseDotNet@2
  inputs:
    version: '2.2.x'
    packageType: runtime

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**.*.csproj'
    arguments: '--configuration Release --collect "Code coverage"'

- script: dotnet test --logger trx

- task: PublishTestResults@2
  condition: suddeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

